### 1. 아래 요구사항에 맞게 코드를 작성해주세요.
- Myclass라는 이름으로 인자값 1개를 받을 수 있게 클래스를 만들어 주세요. (4점)
- Myclass의 인자값은 mangling를 사용하세요.(2점)
- Myclass에서 스페셜 메서드(__str__)를 활용하여 해당 클래스로 만든 객체를 print()로 출력 했을 때, "Print: 인자값" 이라고 꾸며줄 수 있도록 하세요.(테스트 코드를 실행시키면 예상결과와 같이 출력되야 합니다) (4점)

In [7]:
# 테스트 코드
c1 = Myclass("test")
print(c1)

# 예상결과 -> print: test

Print: test


In [6]:
# 여기에 코드를 작성하세요
class Myclass:
    def __init__(self, text):
        self.__text = text

    def __str__(self):
        return "Print: {}".format(self.__text)

## 2.생성된 데이터를 활용하여 아래의 조건에 맞게 선형 회귀분석을 하고, 성능평가를 하세요.
(10점)

조건 : random state는 1234, test siz는는 0.2 입니다.
코드 하단에 pred_y와 round(mae,2) 값을 출력하세요

In [4]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'name': ['Manchester City', 'Manchester United', 'Tottenham Hotspur',
                            'Liverpool', 'Chelsea', 'Arsenal', 'Burnley', 'Everton',
                            'Leicester City', 'Newcastle United', 'Crystal Palace',
                            'Bournemouth', 'West Ham United', 'Watford',
                            'Brighton and Hove Albion', 'Huddersfield Town', 'Southampton',
                            'Swansea City', 'Stoke City', 'West Bromwich Albion'],
                   'gf': [106,  68,  74,  84,  62,  74,  36,  44,  56,  39,  45,  45,  48,
                          44,  34,  28,  37,  28,  35,  31],
                   'ga': [27, 28, 36, 38, 38, 51, 39, 58, 60, 47, 55, 61, 68, 64, 54, 58, 56,
                          56, 68, 56],
                   'points': [100,  81,  77,  75,  70,  63,  54,  49,  47,  44,  44,  44,  42,
                              41,  40,  37,  36,  33,  33,  31]

                   })
df

name   gf  ga  points
0            Manchester City  106  27     100
1          Manchester United   68  28      81
2          Tottenham Hotspur   74  36      77
3                  Liverpool   84  38      75
4                    Chelsea   62  38      70
5                    Arsenal   74  51      63
6                    Burnley   36  39      54
7                    Everton   44  58      49
8             Leicester City   56  60      47
9           Newcastle United   39  47      44
10            Crystal Palace   45  55      44
11               Bournemouth   45  61      44
12           West Ham United   48  68      42
13                   Watford   44  64      41
14  Brighton and Hove Albion   34  54      40
15         Huddersfield Town   28  58      37
16               Southampton   37  56      36
17              Swansea City   28  56      33
18                Stoke City   35  68      33
19      West Bromwich Albion   31  56      31

In [5]:
from sklearn import linear_model
# 학습 데이터와 테스트 데이터를 나눠주는 모듈
from sklearn.model_selection import train_test_split
# 모델을 평가해주는 모듈
from sklearn.metrics import mean_absolute_error

In [6]:
# 2. 데이터 전처리 1 : 독립변수 종속변수 나누기
df_x = df[["gf", "ga"]]
df_y = df[["points"]]

In [7]:
train_x, test_x, train_y, test_y = train_test_split(
    df_x, df_y, test_size=0.2, random_state=1234)

In [8]:
model = linear_model.LinearRegression()

In [9]:
model.fit(train_x, train_y)

LinearRegression()

In [32]:
pred_y = model.predict(test_x)

In [30]:
pred_y

array([[80.7291084 ],
       [39.48577501],
       [76.20087983],
       [40.80603755]])

In [16]:
pred_y.dtype

dtype('float64')

In [34]:
# pred_y = np.around(pred_y.flatten()).astype("int")
# pred_y
pred_y = pred_y.flatten()

In [35]:
pred_y

array([80.7291084 , 39.48577501, 76.20087983, 40.80603755])

In [36]:
test_y["points"].values

array([75, 41, 77, 36])

In [37]:
mae = mean_absolute_error(test_y, pred_y)
mae

3.212122775849208

In [27]:
test_y

points
3       75
13      41
2       77
16      36

In [38]:
ls1 = [1, 2, 3]
ls2 = [3, 5, 7]
ls3 = [6, 5, 4]

In [44]:
def map_func(func, *args):
    return [func(*datas) for datas in zip(*args)]

In [45]:
map_func(lambda x, y, z: x+y+z, ls1, ls2, ls3)

[1, 2, 3] [3, 5, 7] [6, 5, 4]


[10, 12, 14]

In [48]:
np.random.seed(0)
data = pd.Series(np.random.randint(1, 10, size=5), index=list('ABCDE'))

In [49]:
data

A    6
B    1
C    4
D    4
E    8
dtype: int64

In [50]:
result = data+2
result['B'] = 10
result = result+3
result['B']

13