P 213 파이썬을 사용한 특이값 분해

In [1]:
from numpy.linalg import svd

In [13]:
A = np.array([[3, 1], [1, 3], [1, 1]])

# U : 왼쪽특이벡터행렬
# S : 대각행렬이 아니라, 특이값이 1차원 배열로 나옴 
# VT : 오른쪽 특이 벡터 행렬(Transpose 된 상태)

# 축소형으로 구하고 싶으면, svd(A, full_metrices = False)
U, S, VT = svd(A)

In [8]:
U

array([[-6.66666667e-01,  7.07106781e-01, -2.35702260e-01],
       [-6.66666667e-01, -7.07106781e-01, -2.35702260e-01],
       [-3.33333333e-01,  5.92577380e-18,  9.42809042e-01]])

In [9]:
S

array([4.24264069, 2.        ])

In [12]:
np.diag(S, 1)[:, 1:]

array([[4.24264069, 0.        ],
       [0.        , 2.        ],
       [0.        , 0.        ]])

In [10]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [14]:
B = np.array([[3, 2, 2], [2, 3, -2]])
C = np.array([[2, 3], [1, 3], [0, 0], [0, 0]])

In [40]:
U1, S1, VT1 = svd(B, full_matrices=False)
U2, S2, VT2 = svd(C)

In [35]:
U1

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [37]:
diag_1 = np.diag(S1, 0)
# diag_1 = np.append(diag_1, [[0],[0]], axis = 1)
diag_1

array([[5., 0.],
       [0., 3.]])

In [38]:
VT1

array([[-7.07106781e-01, -7.07106781e-01, -6.47932334e-17],
       [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01]])

In [39]:
U1 @ diag_1 @ VT1

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

In [42]:
U2

array([[-0.75336353, -0.65760429,  0.        ,  0.        ],
       [-0.65760429,  0.75336353,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [53]:
diag_2 = np.diag(S2)
diag_2 = np.append(diag_2,[[0, 0], [0, 0]],axis= 0)
diag_2

array([[4.75413522, 0.        ],
       [0.        , 0.63102959],
       [0.        , 0.        ],
       [0.        , 0.        ]])

In [54]:
VT2

array([[-0.45525237, -0.89036244],
       [-0.89036244,  0.45525237]])

In [55]:
U2 @ diag_2 @ VT2

array([[2., 3.],
       [1., 3.],
       [0., 0.],
       [0., 0.]])