In [1]:
np.zeros((3, 1))

array([[0.],
       [0.],
       [0.]])

In [2]:
np.ones((3, 1))

array([[1.],
       [1.],
       [1.]])

In [3]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [4]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.array([[1, 2], [2, 3]])

array([[1, 2],
       [2, 3]])

In [7]:
np.array([[1, 2], [2, 3]]).T

array([[1, 2],
       [2, 3]])

### P85 2.2 벡터와 행렬의 연산

In [8]:
# 덧셈
x = np.array([10, 11, 12, 13, 14])
y = np.array([0, 1, 2, 3, 4])

In [9]:
x + y

array([10, 12, 14, 16, 18])

In [10]:
x - y

array([10, 10, 10, 10, 10])

In [12]:
np.array([[5, 6], [7, 8]]) + np.array([[10, 20], [30, 40]]) 

array([[15, 26],
       [37, 48]])