### quiz의
- 100~130 까지 랜덤한 숫자를 가지를 8*8 행렬을 만들고, 
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환. 
- 랜덤한 행렬 데이터 np.random(100, 130, size=(8, 8))
- 위 조건에 맞지 않는 데이터는 랜덤하게 생성된 정수로 출력
- 데이터 타입 변경 함수 ndarray.astype()

In [2]:
import numpy as np

In [59]:
datas = np.random.randint(100, 130, size = (8, 8))
datas

array([[107, 108, 103, 129, 129, 119, 107, 118],
       [113, 119, 115, 124, 127, 114, 105, 121],
       [125, 127, 110, 106, 114, 104, 113, 128],
       [126, 105, 103, 104, 119, 129, 102, 112],
       [121, 127, 103, 107, 126, 103, 128, 110],
       [111, 105, 126, 107, 125, 119, 117, 127],
       [104, 117, 114, 120, 129, 113, 108, 126],
       [123, 125, 106, 128, 122, 120, 125, 117]])

In [60]:
data1 = np.array([1, 2, 3])
data2 = [True, False, True]
data1[data2]

array([1, 3])

In [ ]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 T, F, Matrix 생성

In [ ]:
# 데이터 타입을 str으로 변환
# T, F, Matrix를 이용하여 특정 조건의 데이터를 선택 후 브로드캐스팅하게 값을 대입. 

In [67]:
mask_5 = (quiz % 5) == 0
mask_3 = (quiz % 3) == 0
mask_15 = (quiz % 15) == 0

In [71]:
data_str = datas.astype(str)

In [78]:
np.where(mask_5, "buz", np.where(mask_3, "fiz", np.where(mask_15, "fbz", data_str)))

array([['fiz', '108', '103', 'fiz', 'buz', '119', '107', 'buz'],
       ['113', 'fiz', 'fiz', 'fiz', '127', 'buz', '105', '121'],
       ['buz', '127', '110', 'buz', '114', 'fiz', 'fiz', '128'],
       ['buz', '105', 'buz', '104', '119', 'buz', '102', '112'],
       ['121', '127', '103', '107', 'buz', '103', 'fiz', 'buz'],
       ['111', '105', 'fiz', '107', '125', '119', 'fiz', 'fiz'],
       ['fiz', '117', 'fiz', '120', '129', 'fiz', '108', '126'],
       ['buz', 'buz', '106', 'fiz', '122', '120', '125', '117']],
      dtype='<U21')

### Quiz 
- 1~20까지 랜덤한 숫자를 가지를 5*5 행렬 생성
- 최댓값에는 MAX, 최솟값에는 MIN문자열이 들어가도록 치환하는 코드를 작성
- 최댓값, 최솟값 함수 
```
np.min(ndarray), np.max(ndarray)
```

In [115]:
datas = np.random.randint(1, 20, (5, 5))
datas

array([[12, 17, 17, 16, 15],
       [10, 13, 12,  1, 13],
       [ 6,  7,  3,  7,  3],
       [ 2,  6, 18,  9,  8],
       [16,  5, 16,  6,  9]])

In [103]:
np.max(datas)

18

In [119]:
mask_max, mask_min = (datas==np.max(datas)), (datas == np.min(datas))

In [106]:
datas = datas.astype(str)
np.where(mask_max, "MAX", np.where(mask_min, "MIN", datas))

array([['MIN', '5', '11', 'MIN', '17'],
       ['3', '13', '2', 'MAX', '17'],
       ['15', '9', '7', '4', '4'],
       ['8', '5', '15', 'MAX', '5'],
       ['17', '10', 'MAX', '17', '10']], dtype='<U21')

### linspace, logspace
- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [121]:
# linspace
np.linspace(0, 100, 5) #0, 100 그리고 3등분 

array([  0.,  25.,  50.,  75., 100.])

In [123]:
#logspace
# log10(x1) = 2, log10(x1) = 3, log10(x1) = 4
# 2에서 4까지 3등분 하면 2, 3, 4 가 되잖아. 그 2, 3, 4를 x1, x2, x3에 넣은 값이야. 
np.logspace(2, 4, 3) 

array([  100.,  1000., 10000.])

In [ ]:
# 30세에 연봉이 $100000 일 때 60세의 연봉이 $1000000일 때, 
# 연봉이 선형으로 증가, 지수함수로 증가하는 두 경우에서의 40, 50세 연봉을 출력

In [125]:
age_30 = 100000
age_60 = 1000000

In [126]:
np.linspace(age_30, age_60, 4)

array([ 100000.,  400000.,  700000., 1000000.])

In [129]:
# np.logspace(age_30, age_60, 4) 
# 이렇게 쓰면 안되지. 
np.logspace(np.log10(age_30), np.log10(age_60), 4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

### 2. numpy random
- seed : 랜덤 설정값(시드 값이 같으면, 랜덤하게 섞이지만 똑같은 랜덤 값이 뽑힘)
- rand : 균등분포로 난수를 발생(0~10까지 뽑힐 확률 비슷하게)
- randn : 정규분포로 난수를 발생(0에서 가까울수록 확률 높게)
- randint : 균등분포로 정수값을 발생
- shuffle : 행렬 데이터를 섞어 줍니다. 
- choice : 특정 확률로 데이터를 선택

In [130]:
#seed
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)
np.random.seed(1)
result2 = np.random.randint(10, 100, 10)
np.random.seed(2)
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [138]:
np.random.rand(10)

array([0.79740494, 0.2693888 , 0.58268489, 0.02555094, 0.66220202,
       0.38752343, 0.4970738 , 0.41490584, 0.3508719 , 0.55097791])

In [132]:
np.random.randn(10)

array([-0.0191305 ,  1.17500122, -0.74787095,  0.00902525, -0.87810789,
       -0.15643417,  0.25657045, -0.98877905, -0.33882197, -0.23618403])

In [152]:
# shuffle
r = np.random.randint(1, 10, (3, 4))
r

array([[6, 2, 4, 4],
       [4, 3, 7, 6],
       [6, 3, 6, 7]])

In [156]:
np.random.shuffle(r) 
r

# 지금 보면 제일 바깥쪽만 랜덤하게 바뀜
# 이걸 싹다 바꾸고 싶으면, 1차원으로 만든 다음에 셔플 돌리고, 다시 reshape으로 원래대로 만들면 됨. 

array([[6, 2, 4, 4],
       [4, 3, 7, 6],
       [6, 3, 6, 7]])

In [185]:
# choice
# 각 숫자의 확률을 써주면 됨. 
# 5는 0~5, 뒤에 10은 갯수 5 직전 4까지. 
# choice(a, size=None, replace=True, p=None)
# Generates a random sample from a given 1-D array

np.random.choice(5, 10, p=[0.1, 0.4, 0.2, 0.2, 0.1])

array([2, 1, 0, 1, 1, 0, 2, 0, 1, 1])

In [186]:
r

array([[6, 2, 4, 4],
       [4, 3, 7, 6],
       [6, 3, 6, 7]])

In [189]:
# unique, unique한 값들 출력
np.unique(r), np.unique(r, return_counts=True)

(array([2, 3, 4, 6, 7]), (array([2, 3, 4, 6, 7]), array([1, 2, 3, 4, 2])))

### 3. 행렬 데이터의 결합
- concatenate

In [191]:
na1 = np.random.randint(10, size=(2, 3))
na2 = np.random.randint(10, size=(3, 2))
na3 = np.random.randint(10, size=(3, 3))

In [194]:
# 세로로 합치기
# 결합하려면 차원이 맞아야지. 
na1, na2, na3

(array([[2, 8, 1],
        [0, 9, 2]]),
 array([[5, 2],
        [4, 6],
        [5, 3]]),
 array([[6, 9, 3],
        [0, 8, 4],
        [0, 2, 1]]))

In [196]:
np.concatenate((na1, na3))

array([[2, 8, 1],
       [0, 9, 2],
       [6, 9, 3],
       [0, 8, 4],
       [0, 2, 1]])

In [197]:
# 가로 결합
np.concatenate((na2, na3), axis = 1)

array([[5, 2, 6, 9, 3],
       [4, 6, 0, 8, 4],
       [5, 3, 0, 2, 1]])

In [199]:
# c_, r_로도 결합 가능함. 
# c : column, r : row
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [200]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [201]:
# split, var, std, mean ...